## 第3次作业

1、已掌握： .csv 文件读写

2、今日新增：学会如何查看局部数据，简单筛选符合条件的数据

### 1、温故：读写.csv 文件

In [183]:
import pandas as pd
file_path = "./pokemon_data.csv"
df = pd.read_csv(file_path,index_col = 0)
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False
8,Wartortle,Water,NaN,59,63,80,65,80,58,1,False
9,Blastoise,Water,NaN,79,83,100,85,105,78,1,False
9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False
11,Metapod,Bug,NaN,50,20,55,25,25,30,1,False
12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
19,Rattata,Normal,NaN,30,56,35,25,35,72,1,False
20,Raticate,Normal,NaN,55,81,60,50,70,97,1,False
21,Spearow,Normal,Flying,40,60,30,31,31,70,1,False
22,Fearow,Normal,Flying,65,90,65,61,61,100,1,False
23,Ekans,Poison,NaN,35,60,44,40,54,55,1,False
24,Arbok,Poison,NaN,60,85,69,65,79,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...
700,Sylveon,Fairy,NaN,95,65,65,110,130,60,6,False
701,Hawlucha,Fighting,Flying,78,92,75,74,63,118,6,False
702,Dedenne,Electric,Fairy,67,58,57,81,67,101,6,False
703,Carbink,Rock,Fairy,50,50,150,50,150,50,6,False
704,Goomy,Dragon,NaN,45,50,35,55,75,40,6,False
705,Sliggoo,Dragon,NaN,68,75,53,83,113,60,6,False
706,Goodra,Dragon,NaN,90,100,70,110,150,80,6,False
707,Klefki,Steel,Fairy,57,80,91,80,87,75,6,False
708,Phantump,Ghost,Grass,43,70,48,50,60,38,6,False
709,Trevenant,Ghost,Grass,85,110,76,65,82,56,6,False
710,PumpkabooAverage Size,Ghost,Grass,49,66,70,44,55,51,6,False
710,PumpkabooSmall Size,Ghost,Grass,44,66,70,44,55,56,6,False
710,PumpkabooLarge Size,Ghost,Grass,54,66,70,44,55,46,6,False
710,PumpkabooSuper Size,Ghost,Grass,59,66,70,44,55,41,6,False
711,GourgeistAverage Size,Ghost,Grass,65,90,122,58,75,84,6,False
711,GourgeistSmall Size,Ghost,Grass,55,85,122,58,75,99,6,False
711,GourgeistLarge Size,Ghost,Grass,75,95,122,58,75,69,6,False
711,GourgeistSuper Size,Ghost,Grass,85,100,122,58,75,54,6,False
712,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
713,Avalugg,Ice,NaN,95,117,184,44,46,28,6,False
714,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False
715,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False
716,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True
717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### 2、查看数据的头行、尾行

In [184]:
df.head(3)
print(type(df.head(3)))

<class 'pandas.core.frame.DataFrame'>

In [185]:
# 查看尾部的n行，这里n填了5
df.tail(4)
print(type(df.tail(3)))

<class 'pandas.core.frame.DataFrame'>

In [186]:
# 请留意数据类型是dataframe
print(type(df.head(5)))
print(type(df.tail(5)))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

## 查看单列数据的2种方法

In [187]:
# 查看单列方法1
df["Name"]

print(df["Name"].head(5))
print("*"*30)

print(df[["Name"]].head(5))
print("*"*30)

print(type(df["Name"]))
print(type(df[["Name"]]))
print("*"*30)

print(df["Name"].ndim)
print(df[["Name"]].ndim)
print("*"*30)

print(df["Name"].shape)
print(df[["Name"]].shape)

#
1                Bulbasaur
2                  Ivysaur
3                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object
******************************
                    Name
#
1              Bulbasaur
2                Ivysaur
3               Venusaur
3  VenusaurMega Venusaur
4             Charmander
******************************
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
******************************
1
2
******************************
(800,)
(800, 1)

In [188]:
# 请留意单列的数据类型，是Series
print(type(df['Name']))

<class 'pandas.core.series.Series'>

In [189]:
# 查看单列方法2
df[['Name']]
len(df[["Name"]])

800

In [190]:
# 请留意单列的数据类型，是dataframe
print(type(df[['Name']]))

<class 'pandas.core.frame.DataFrame'>

#### 思考题：当筛选出来的数据是 dataframe，且打印结果很长时，如何只查看部分数据，让打印没那么庞大？

In [191]:
# 答案

df[['Name']].head(2)

        Name
#
1  Bulbasaur
2    Ivysaur

#### 思考题：如何查看数据有哪些行和列？

In [192]:
# 答案

print(df.index)
print(df.shape[0])

Int64Index([  1,   2,   3,   3,   4,   5,   6,   6,   6,   7,
            ...
            714, 715, 716, 717, 718, 719, 719, 720, 720, 721],
           dtype='int64', name='#', length=800)
800

In [193]:
print(df.columns)
print(df.shape[1])

Index(['Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
11

#### 思考题：如何 行或列 的数据转换为 列表？

In [194]:
# 答案：
x = df.columns
alist = list(x)
print(alist)
print(type(x))
print(type(alist))

['Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary']
<class 'pandas.core.indexes.base.Index'>
<class 'list'>

In [195]:
for i in x:
    print(i)

Name
Type 1
Type 2
HP
Attack
Defense
Sp. Atk
Sp. Def
Speed
Generation
Legendary

## 筛选查看多列数据

In [196]:
# 查看多列，df[] 的内部是一个由列名构成的列表

# 现在回头看查看单列的方法2，是否更好理解了？
# 对于下面这行代码的.head(5)的作用是否能理解了？

df[['Name','Type 1','Speed']].head(5)

                    Name Type 1  Speed
#
1              Bulbasaur  Grass     45
2                Ivysaur  Grass     60
3               Venusaur  Grass     80
3  VenusaurMega Venusaur  Grass     80
4             Charmander   Fire     65

In [197]:
# 请留意，多列构成的数据，是dataframe

print(type(df[['Name','Type 1','Speed']]))

<class 'pandas.core.frame.DataFrame'>

## 实操练习

1、 speed > 100 的pokemon 共有多少个？

2、90< speed < 100 的 pokemon 的 name 是哪些？

In [198]:
# 答案
#print(df["Speed"])
alist = list(df["Speed"])
sum = 0
for i in alist:
    if i > 100:    # 对吗？为什么？自己试试代码，查看为什么。
        sum += 1
print(sum)

106

In [199]:
len(df[(df['Speed']>100)]) #现在对吗？

106

In [242]:
# 答案,符合&表示“且” ，符号|表示“或”，符号 ~表示“非”，注意不能用python原生的 （and or not） 来表示逻辑关系
dfx = df[(df['Speed']>90) & (df['Speed']<100)]


for i in dfx['Name']:
    print(i,end=', ')

print(len(dfx))
dfy =  df[(df['Speed']<=90) | (df['Speed']>=100)]
print(len(dfy))

df.loc[:,["Speed"]]

Raticate, Diglett, Primeape, Arcanine, Haunter, Jynx, Magmar, Xatu, Yanma, Murkrow, Houndoom, Elekid, Grovyle, Plusle, Minun, Sharpedo, Luvdisc, Rayquaza, Pachirisu, Chatot, GarchompMega Garchomp, Drapion, Lumineon, Electivire, Yanmega, Leafeon, Gliscor, Rotom, Uxie, Unfezant, Leavanny, Basculin, Krookodile, DarmanitanStandard Mode, Sigilyph, Swanna, Sawsbuck, Haxorus, Hydreigon, LandorusTherian Forme, Kyurem, KyuremBlack Kyurem, KyuremWhite Kyurem, Genesect, Frogadier, GourgeistSmall Size, Xerneas, Yveltal, Zygarde50% Forme, 49
751

     Speed
#
1       45
2       60
3       80
3       80
4       65
5       80
6      100
6      100
6      100
7       43
8       58
9       78
9       78
10      45
11      30
12      70
13      50
14      35
15      75
15     145
16      56
17      71
18     101
18     121
19      72
20      97
21      70
22     100
23      55
24      80
..     ...
700     60
701    118
702    101
703     50
704     40
705     60
706     80
707     75
708     38
709     56
710     51
710     56
710     46
710     41
711     84
711     99
711     69
711     54
712     28
713     28
714     55
715    123
716     99
717     99
718     95
719     50
719    110
720     70
720     80
721     70

[800 rows x 1 columns]

如果上方代码中的()去掉会怎样，`df[df['Speed']>90 & df['Speed']<100]` 试试看？

上述 逻辑关系是 “且”，如果想要实现 “或”、“非” 怎么写？搜索一下找答案吧

## 预告 下次作业

想要知道 Speed 的取值有哪些？每个不同Speed值，有多少 pokemon ？如何对统计值进行排序？

分组统计还有哪些复杂但实用的玩法？

In [20]:
#  Speed 的取值有哪些？每个不同Speed值，有多少 pokemon ？
rlt = df[['Name','Speed']].groupby(by='Speed').count()